# Generated by Django 5.0.5 on 2024-05-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('contenido', models.CharField(max_length=500)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
